require(rCharts)

shinyServer(function(input, output) {
  
  datasetInput <- reactive({
    switch(input$dataset,
           "diamonds"=input$diamonds,
           "economics_long"=input$economics_long,
           "luv_colours"=input$luv_colours,
           "mpg"=input$mpg,
           "presidential"=input$presidential,
           "txhousing"=input$txhousing,
           "BJsales"=input$BJsales,
           "BOD"=input$BOD,
           "ChickWeight"=input$ChickWeight,
           "EuStockMarkets"=input$EuStockMarkets,
           "HairEyeColor"=input$HairEyeColor,
           "Harman74.cor"=input$Harman74.cor,
           "InsectSprays"=input$InsectSprays,
           "LakeHuron"=input$LakeHuron,
           "Loblolly"=input$Loblolly,
           "Orange"=input$Orange,
           "PlantGrowth"=input$PlantGrowth,
           "Seatbelts"=input$Seatbelts,
           "Titanic"=input$Titanic,
           "UCBAdmissions"=input$UCBAdmissions,
           "UKgas"=input$UKgas,
           "USArrests"=input$USArrests,
           "USPersonalExpenditure"=input$USPersonalExpenditure,
           "VADeaths"=input$VADeaths,
           "WorldPhones"=input$WorldPhones,
           "airmiles"=input$airmiles,
           "anscombe"=input$anscombe,
           "attitude"=input$attitude,
           "beaver1 (beavers)"=input$beaver1 (beavers),
           "cars"=input$cars,
           "co2"=input$co2,
           "discoveries"=input$discoveries,
           "euro"=input$euro,
           "eurodist"=input$eurodist,
           "fdeaths (UKLungDeaths)"=input$fdeaths (UKLungDeaths),
           "freeny.x (freeny)"=input$freeny.x (freeny),
           "infert"=input$infert,
           "iris3"=input$iris3,
           "ldeaths (UKLungDeaths)"=input$ldeaths (UKLungDeaths),
           "longley"=input$longley,
           "mdeaths (UKLungDeaths)"=input$mdeaths (UKLungDeaths),
           "mtcars"=input$mtcars,
           "nottem"=input$nottem,
           "occupationalStatus"=input$occupationalStatus,
           "presidents"=input$presidents,
           "quakes"=input$quakes,
           "rivers"=input$rivers,
           "sleep"=input$sleep,
           "stack.x (stackloss)"=input$stack.x (stackloss),
           "state.abb (state)"=input$state.abb (state),
           "state.center (state)"=input$state.center (state),
           "state.name (state)"=input$state.name (state),
           "state.x77 (state)"=input$state.x77 (state),
           "sunspot.year"=input$sunspot.year,
           "swiss"=input$swiss,
           "trees"=input$trees,
           "volcano"=input$volcano,
           "women"=input$women,
           "economics"=input$economics,
           "faithfuld"=input$faithfuld,
           "midwest"=input$midwest,
           "msleep"=input$msleep,
           "seals"=input$seals,
           "AirPassengers"=input$AirPassengers,
           "BJsales.lead (BJsales)"=input$BJsales.lead (BJsales),
           "CO2"=input$CO2,
           "DNase"=input$DNase,
           "Formaldehyde"=input$Formaldehyde,
           "Harman23.cor"=input$Harman23.cor,
           "Indometh"=input$Indometh,
           "JohnsonJohnson"=input$JohnsonJohnson,
           "LifeCycleSavings"=input$LifeCycleSavings,
           "Nile"=input$Nile,
           "OrchardSprays"=input$OrchardSprays,
           "Puromycin"=input$Puromycin,
           "Theoph"=input$Theoph,
           "ToothGrowth"=input$ToothGrowth,
           "UKDriverDeaths"=input$UKDriverDeaths,
           "USAccDeaths"=input$USAccDeaths,
           "USJudgeRatings"=input$USJudgeRatings,
           "UScitiesD"=input$UScitiesD,
           "WWWusage"=input$WWWusage,
           "ability.cov"=input$ability.cov,
           "airquality"=input$airquality,
           "attenu"=input$attenu,
           "austres"=input$austres,
           "beaver2 (beavers)"=input$beaver2 (beavers),
           "chickwts"=input$chickwts,
           "crimtab"=input$crimtab,
           "esoph"=input$esoph,
           "euro.cross (euro)"=input$euro.cross (euro),
           "faithful"=input$faithful,
           "freeny"=input$freeny,
           "freeny.y (freeny)"=input$freeny.y (freeny),
           "iris"=input$iris,
           "islands"=input$islands,
           "lh"=input$lh,
           "lynx"=input$lynx,
           "morley"=input$morley,
           "nhtemp"=input$nhtemp,
           "npk"=input$npk,
           "precip"=input$precip,
           "pressure"=input$pressure,
           "randu"=input$randu,
           "rock"=input$rock,
           "stack.loss (stackloss)"=input$stack.loss (stackloss),
           "stackloss"=input$stackloss,
           "state.area (state)"=input$state.area (state),
           "state.division (state)"=input$state.division (state),
           "state.region (state)"=input$state.region (state),
           "sunspot.month"=input$sunspot.month,
           "sunspots"=input$sunspots,
           "treering"=input$treering,
           "uspop"=input$uspop,
           "warpbreaks"=input$warpbreaks
    )
  })
  
  output$summary <- renderPrint({
    dataset <- datasetInput()
    summary(dataset)
  })
  
  output$view <- renderTable({
    head(datasetInput(), n = input$obs)
  })
})
